spring:
  application.name: PubiPet
  #資料庫配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pubi_pet
    username: root
    password: password
    hikari:
     minimum-idle: 5
     maximum-pool-size: 10
     connection-timeout: 30000
  profiles.active: dev
# JPA/Hibernate config
  jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.MySQLDialect
  #文件上傳配置
  servlet:
   multipart:
    max-file-size: 10MB
    max-request-size: 100MB
  #email config
  mail:
   host: smtp.gmail.com
   port: 587
   username: jann84920@gmail.com
   password: kcdahwggfxytloqc
   properties.mail.smtp.auth: true
   properties.mail.smtp.starttls.enable: true


server:
  port: 8080
#  servlet.context-path: /PubiPet

# log
#logging.level.org.springframework.boot.autoconfigure=ERROR
#logging.level.org.springframework=DEBUG
#logging.level.com.pubi=TRACE
logging:
  level.org.hibernate.engine.jdbc.env.internal: DEBUG
  file.name: /logs/pubi-pet.log
#  pattern.console: %d{yyyy-MM-dd HH:mm:ss} - %msg%n


